"""
Task 3 Overview
Overview
The goal of this task is to mine the data set to discover the common/popular dishes of a particular cuisine. Typically when you go to try a new cuisine, you don’t know beforehand the types of dishes that are available for that cuisine. For this task, we would like to identify the dishes that are available for a cuisine by building a dish recognizer.

Instructions
Before you begin, make sure you have downloaded the data set and any additional tools you wish to use, as described on the Data Set and Toolkit Acquisition page.

Some questions to consider when building the dish recognizer are the following:

What types of dishes are present in the reviews for a cuisine?

Are there any surprising dishes in the list you annotated?

What types of dishes were you able to find?

You must complete the following specific tasks.

Task 3.1: Manual Tagging

You are given a list of candidate dish names,which are all frequent (at least 10 times in corresponding corpus), automatically generated by the auto-labeling process of SegPhrase. The list can be found in the manualAnnotationTask.zipfile. Some of the dish names are verified by an outside knowledge base such that they are all good phrases, and some of them might be good dish names. However, some of the labels might be wrong. Therefore, your task here is to refine the label list for one cuisine. You could modify/add some phrases. Here are some actions you may take:

Remove a false positive non-dish name phrase (recommended), e.g., hong kong 1 could be removed in Chinese cuisine.

Change a false positive non-dish name phrase to a negative label, e.g., hong kong 1 could be modified as hong kong 0.

Remove a false negative dish name phrase, e.g., wonton strips 0 could be removed in Chinese cuisine.

Change a false negative dish name phrase to a positive label (recommended), e.g., wonton strips 0 could be modified as wonton strips 1.

Add some new annotated phrases in the same format.

Tip: Notice that the character between a phrase and its label is a tab instead of a space.

Remember that the tools we are using were originally designed for general phrase mining instead of dish name mining. Therefore, it will be much safer if we just remove those ambiguous labels, while aggressively changing them into opposites may lead to some undetermined risks, although it is still worth a try.

Task 3.2: Mining Additional Dish Names

Once you have a list of dish names, it is likely that many dish names are still missing. In this step, you would expand the list of dishes by using other pattern mining techniques and/or word association methods.

For example, ToPMine, as we mentioned in the previous pattern mining course, is an unsupervised frequent pattern-based phrase mining algorithm. It merges consecutive words based on statistical significance (stopwords will be firstly removed and be put back later). The most state of the art framework is SegPhrase. SegPhrase will need the (refined) labels in the first task. SegPhrase has a classifier to assign a quality score to each phrase candidate based on their statistical features. The classification procedure will be enhanced by phrasal segmentation results. These two parts could mutually enhance each other.

Another approach to possibly extending the dish names is using word association. You have previously learned and implemented methods to judge word associations (paradigmatic & syntagmatic relations), such as Mutual Information. There are also some more state-of-the-art methods such as word2vec, which you are welcome to experiment with.

Submission
For Task 3, you need to submit a report.

Report in PDF format. We suggest that it be 1-2 pages long. The report will be peer-graded. Your report will need to include the following elements:

A brief description of what you did, including the pattern mining/word association techniques used, how you revised the labels we provided and how these modifications improved the results (you can try to judge by simply looking at it or show several case studies), the parameters you used, how you applied the models to the specific cuisine, and any interesting findings discovered during your tries. Your description should be detailed enough to allow others to replicate your work.

Your opinions about whether the results you generated make sense or are useful in any way.

Submit Task 3

Evaluation
Your peers will evaluate your submission based on the Task 3 Rubric. This assignment is worth 10 points. The evaluation period will begin immediately after you submit your report. You must evaluate three of your peers' submissions.

Evaluate Task 3

Deadlines
See the Syllabus for detailed information about deadlines for this task.

Getting Help
You can discuss Task 3 with your peers in the Course Campuswire under the tag "task3". We have provided tools in various languages to help you accomplish tasks on the Data and Toolkit Acquisition page. You may use these tools or are free to experiment with other ways of accomplishing the task. For information specific to this task, see below.

Useful Resources for Task 3
Java: We have supplied you with a Jar file in task1JavaTools.zip that when given a cuisine file and a list of phrases will compute the Mutual Information for the words in the cuisine file. To learn more about this tool you can find a README accompanied with the tool.

ToPMine(Click on the Code and Datasets tab on the page to find the ToPMine download.)

SegPhrase

References
[1] El-Kishky, A., et al. (2014). Scalable topical phrase mining from text corpora. Proceedings of the VLDB Endowment, 8(3): 305-316.

[2] Liu*, J., Shang*, J., Wang, C., Ren, X., & Han, J. (2015, May). Mining quality phrases from massive text corpora,” Proceedings of 2015 ACM SIGMOD International Conference on Management of Data (SIGMOD'15). Melbourne, Australia. (* equally contributed)

[3]Goldberg, Y., & Levy, O. (2014). word2vec explained: Deriving Mikolov et al.'s negative-sampling word-embedding method. arXiv preprint arXiv:1402.3722.
"""